In [ ]:
# ## for colab
# # !pip install -U -q PyDrive

# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

In [ ]:
# ## for colab
# # Load the Drive helper and mount
# from google.colab import drive

# # This will prompt for authorization.
# drive.mount('/content/drive')

In [7]:
## common imports
import numpy as np
import pandas as pd
import os
import pickle
import warnings
warnings.filterwarnings("ignore")
from datetime import datetime

In [8]:
## to plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

## to make this notebook's output stable across runs
np.random.seed(42)

In [9]:
## import sklearn packages
# from sklearn.metrics import precision_score, recall_score
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
# from sklearn.metrics import roc_curve, auc, roc_auc_score
# from sklearn.metrics import precision_recall_curve

# 04a_LinearModel

In [77]:
## read the data
with open('../final_project_data/insurance_clf_data_new.pickle','rb') as file:
    df_all = pickle.load(file)

In [78]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1794135 entries, 0 to 1795671
Columns: 297 entries, Var07 to id
dtypes: float64(28), int64(40), object(1), uint8(228)
memory usage: 1.3+ GB

In [80]:
df_all.iloc[0:10, :].transpose()

,0,1,2,3,4,5,6,7,8,9
Var07,0,0,0,0,0,0,0,0,0,0
Var10,2,2,2,2,2,5,5,5,5,4
Var26,15,13,15,13,13,13,8,8,8,6
Var27,16,8,16,8,8,8,5,5,5,5
Var28,9,9,9,9,9,9,9,9,9,9
Var29,10,8,10,8,8,8,4,4,4,4
Var30,0,0,0,0,1,0,0,0,0,0
Var31,0,0,0,0,1,0,0,0,0,0
Var32,0,0,0,0,0,0,0,0,0,0
Var33,0,0,0,0,0,0,0,0,0,0
Var34,0,0,0,0,0,0,0,0,0,0
Var35,0,0,0,0,0,0,0,0,0,0
Var42,0,0,0,0,0,0,0,0,0,0
Var50,2,2,2,2,1,1,3,3,3,2
c08,0,0,0,0,0,0,0,0,0,0
c09,0,0,0,0,0,0,0,0,0,0
c10,0,0,0,0,0,0,0,0,0,0
c11,0,0,0,0,0,0,0,0,0,0
c12,0,0,0,0,0,0,0,0,0,0
c15,0,0,0,0,0,0,0,0,0,0
c18,1,1,1,1,0,0,0,0,0,0
c19,7,7,7,7,7,3,2,2,2,4
c27,3,3,3,3,0,4,0,0,0,0
Var54,5,5,5,5,5,5,5,5,5,5
Var02,38,38,38,38,38,35,35,35,35,37
Var04,37,37,38,38,37,37,35,35,35,35
Var05,23,23,23,23,4,5,8,8,8,13
Var06,8,8,8,8,8,30,8,8,8,8
Var08,36,36,36,36,39,36,39,39,39,39
Var09,36,36,36,36,39,36,39,39,39,39
...,...,...,...,...,...,...,...,...,...,...
c36_N,1,1,1,1,1,1,0,1,1,1
c36_Y,0,0,0,0,0,0,1,0,0,0
c37_N,1,1,1,1,1,1,1,1,1,1
c37_Y,0,0,0,0,0,0,0,0,0,0
Var56_A,1,1,1,1,1,1,1,1,1,1
Var56_B,0,0,0,0,0,0,0,0,0,0
Var10_NA,0,0,0,0,0,0,0,0,0,0
Var26_NA,0,0,0,0,0,0,0,0,0,0
Var28_NA,0,0,0,0,0,0,0,0,0,0
c08_NA,0,0,0,0,0,0,0,0,0,0
c11_NA,0,0,0,0,0,0,0,0,0,0
c12_NA,0,0,0,0,0,0,0,0,0,0
c15_NA,0,0,0,0,0,0,0,0,0,0
c18_NA,0,0,0,0,0,0,0,0,0,0
c19_NA,0,0,0,0,0,0,0,0,0,0
c27_NA,0,0,0,0,0,0,0,0,0,0
Var12_NA,0,0,0,0,0,0,0,0,0,0
c04_NA,1,1,1,1,0,0,0,0,0,0
c05_NA,0,0,0,0,0,0,0,0,0,1
c16_NA,0,0,0,0,0,0,0,0,0,1
c26_NA,0,0,0,0,0,0,0,0,0,0
c34_NA,0,0,0,0,0,0,0,0,0,0
c38_NA,0,0,0,0,0,0,0,0,0,1
c39_NA,0,0,0,0,0,0,0,0,0,1
c40_NA,0,0,0,0,0,0,0,0,0,1
train,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y
Var47,1,0,1,0,0,0,0,1,0,0
pred_s,89,19,87,17,4,11,12,8,8,31
uniqueID,352373,352373,765898,765898,138374,25235,54047,54047,54047,565051
id,8747,8747,8747,8747,40261,51093,51093,51093,51093,45195

#### The target variable is called Var47.  It is given as 0 or 1 and we would expect you to predict the probability that it is 0 or 1.  The target is not available for the test data.

The predictions of our current model are given in pred_s.  The prediction is not available for the test data.  pred_s is the result of a logistic regression.  There are 20 features in the regression (chosen from Var1-Var42). Note that these features are not necessarily used as linear features.

In [81]:
df_Y = df_all.loc[df_all.train=="Y"]
print(df_Y.shape)

(1646270, 297)

In [82]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df_Y, test_size=0.9, random_state=42)
print(df_train.shape, df_test.shape)

(164627, 297) (1481643, 297)

#### Sampling (This part needs furture improvement)
<p> Limited by our computing resources, we are now using a small sample of data to train models.

<p> Considering stratified sampling?

In [ ]:
# from sklearn.model_selection import StratifiedShuffleSplit

# split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
# for train_index, test_index in split.split(df_Y, df_Y["Var47"]):
#     strat_train_set = df_Y.loc[train_index]
#     strat_test_set = df_Y.loc[test_index]

#### Select input data for training models

In [83]:
## All variables in the transformed dataframe
features = list(df_all)
df_features = pd.DataFrame(np.array(list(df_all)).reshape(27, 11))
df_features

,0,1,2,3,4,5,6,7,8,9,10
0,Var07,Var10,Var26,Var27,Var28,Var29,Var30,Var31,Var32,Var33,Var34
1,Var35,Var42,Var50,c08,c09,c10,c11,c12,c15,c18,c19
2,c27,Var54,Var02,Var04,Var05,Var06,Var08,Var09,Var12,Var15,Var16
3,Var18,Var22,Var24,c04,c05,c16,c26,c34,c35,c38,c39
4,c40,Var01_A,Var01_B,Var01_C,Var03_A,Var03_B,Var03_C,Var03_D,Var03_E,Var03_F,Var03_G
5,Var03_H,Var03_I,Var03_J,Var03_L,Var03_N,Var03_P,Var03_Q,Var03_Z,Var11_A,Var11_B,Var11_C
6,Var11_D,Var11_E,Var11_F,Var11_G,Var11_Z,Var13_A,Var13_B,Var13_C,Var13_D,Var13_E,Var13_F
7,Var13_G,Var13_H,Var13_I,Var13_J,Var13_K,Var13_L,Var13_M,Var13_N,Var13_O,Var13_P,Var13_Q
8,Var13_R,Var13_S,Var13_Z,Var14_A,Var14_B,Var14_C,Var14_D,Var14_E,Var14_F,Var14_Z,Var19_A
9,Var19_B,Var19_C,Var19_D,Var19_E,Var19_F,Var19_G,Var19_Z,Var20_A,Var20_B,Var21_A,Var21_B
10,Var21_C,Var21_D,Var21_Z,Var23_A,Var23_B,Var23_C,Var23_Z,Var25_A,Var25_B,Var25_C,Var25_D
11,Var25_E,Var25_F,Var25_G,Var25_H,Var25_I,Var25_J,Var25_K,Var25_L,Var25_M,Var25_Z,Var48_A
12,Var48_B,Var48_C,Var48_D,Var48_E,Var48_F,Var48_G,Var48_H,Var48_I,Var48_J,Var48_K,Var48_L
13,Var48_M,Var48_N,Var48_O,Var48_P,Var48_Q,Var49_A,Var49_B,Var51_A,Var51_B,Var51_C,Var51_D
14,Var51_E,Var51_F,Var51_G,Var51_H,Var51_I,Var51_J,Var51_L,Var51_M,Var51_N,Var51_P,Var51_Q
15,Var51_Z,Var52_A,Var52_B,Var53_A,Var53_B,Var53_C,Var53_D,Var53_E,Var53_F,Var53_X,Var55_A
16,Var55_B,Var55_C,Var55_D,Var55_E,Var55_F,Var55_G,Var55_X,c01_A,c01_B,c01_C,c01_D
17,c01_F,c01_G,c01_H,c02_A,c02_B,c02_C,c02_D,c02_E,c02_F,c02_G,c02_H
18,c03_A,c03_B,c03_C,c03_D,c03_E,c03_F,c03_G,c03_H,c03_I,c03_J,c03_K
19,c03_L,c06_N,c06_Y,c07_N,c07_Y,c13_A,c13_B,c13_C,c13_D,c13_E,c13_F
20,c13_G,c13_H,c13_I,c14_N,c14_O,c14_Y,c17_A,c17_B,c17_C,c17_E,c17_F
21,c20_N,c20_O,c20_Y,c21_N,c21_O,c21_Y,c22_E,c22_F,c23_N,c23_Y,c24_N
22,c24_Y,c25_A,c25_B,c25_C,c25_D,c25_E,c25_F,c28_A,c28_B,c28_C,c29_A
23,c29_B,c29_C,c30_A,c30_B,c30_C,c31_A,c31_B,c31_C,c32_A,c32_B,c32_C
24,c33_A,c33_B,c33_C,c36_N,c36_Y,c37_N,c37_Y,Var56_A,Var56_B,Var10_NA,Var26_NA
25,Var28_NA,c08_NA,c11_NA,c12_NA,c15_NA,c18_NA,c19_NA,c27_NA,Var12_NA,c04_NA,c05_NA
26,c16_NA,c26_NA,c34_NA,c38_NA,c39_NA,c40_NA,train,Var47,pred_s,uniqueID,id

In [84]:
## setting the inputs the output for our classification task
target = ['Var47']

labels = ['uniqueID', 'id', 'train', 'Var47','pred_s']

variables = ['Var01', 'Var03', 'Var07', 'Var10', 'Var11', 'Var13',
             'Var14', 'Var19', 'Var20', 'Var21', 'Var23', 'Var25', 'Var26',
             'Var27', 'Var28', 'Var29', 'Var30', 'Var31', 'Var32', 'Var33', 
             'Var34', 'Var35', 'Var42', 'Var48', 'Var49', 
             'Var50', 'Var51', 'Var52', 'Var53', 'Var55', 
             'c01', 'c02', 'c03', 'c06', 'c07', 'c08', 'c09', 'c10', 'c11', 'c12', 
             'c13', 'c14', 'c15', 'c17', 'c18', 'c19', 'c20', 'c21', 'c22', 'c23', 
             'c24', 'c25', 'c27', 'c28', 'c29', 'c30', 'c31', 'c32', 'c33', 'c36', 'c37', 
             'Var54', 'Var56', 'Var02', 'Var04', 'Var05', 'Var06', 'Var08', 'Var09', 
             'Var12', 'Var15', 'Var16', 'Var18', 'Var22', 'Var24', 
             'c04', 'c05', 'c16', 'c26', 'c34', 'c35', 'c38', 'c39', 'c40']

In [85]:
## setting the inputs the output for our classification task
features_01 = list(set(features) - set(labels))
print(len(features_01))

292

#### X_train  & y_train

In [97]:
X_train_01 = df_train[features_01].values.astype(np.int)
y_train = df_train[target].values.astype(np.int)
print(X_train_01.shape, y_train.shape)

(164627, 292) (164627, 1)

#### X_test & y_test

In [98]:
X_test_01 = df_test[features_01].values.astype(np.int)
y_test = df_test[target].values.astype(np.int)
print(X_test_01.shape, y_test.shape)

(1481643, 292) (1481643, 1)

In [101]:
X_test_01.dtype

dtype('int8')

#### Performance measurements

In [88]:
# This is a function which outputs a variety of accuracy results. We can use these results to compare models.

from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
def calc_specificity(y_vals, preds, threshes):
    # calculates specificity
    return sum((preds < threshes) & (y_vals == 0)) /sum(y_vals ==0)

def print_report(y_vals, preds, threshes):
    
    auc = roc_auc_score(y_vals, preds)
    accuracy = accuracy_score(y_vals, (preds > threshes))
    recall = recall_score(y_vals, (preds > threshes))
    precision = precision_score(y_vals, (preds > threshes))
    specificity = calc_specificity(y_vals, preds, threshes)
    print('AUC:%.3f'%auc)
    print('accuracy:%.3f'%accuracy)
    print('recall:%.3f'%recall)
    print('precision:%.3f'%precision)
    print('specificity:%.3f'%specificity)
    print(' ')
    return auc, accuracy, recall, precision, specificity

# 04_b. Logistic
<p> Toooo low validation accuracy now.

In [89]:
# ## use a small sample; 30% of training data
# X_train = X0_train_s
# y_train = y0_train_s
# X_test = X0_test
# y_test = y0_test

In [102]:
## 
X_train = X_train_01
y_train = y_train
X_test = X_test_01
y_test = y_test

In [103]:
# prepare Logistic Regression classifier
from sklearn.linear_model import LogisticRegression
logit_clf = LogisticRegression(random_state=42)  
# logit_clf = LogisticRegression(tol=0.0001, C=1.0, random_state=42, max_iter=100,penalty='l1', solver='liblinear',verbose=0)

In [104]:
print(logit_clf)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [105]:
# training and validation
import time
start_time = time.time()
logit_clf.fit(X_train, y_train) 
print("--- %s seconds ---" % (time.time() - start_time))

--- 96.13304805755615 seconds ---

In [106]:
y_train_logit_pred = logit_clf.predict(X_train)
y_test_logit_pred = logit_clf.predict(X_test)

In [107]:
print("Training Accuracy", accuracy_score(y_train, y_train_logit_pred))
print("Test Accuracy", accuracy_score(y_test, y_test_logit_pred))

Training Accuracy 0.7537645708176666
Test Accuracy 0.750773296941301

In [108]:
print(classification_report(y_test, y_test_logit_pred))

              precision    recall  f1-score   support

           0       0.75      0.76      0.75    752531
           1       0.75      0.75      0.75    729112

   micro avg       0.75      0.75      0.75   1481643
   macro avg       0.75      0.75      0.75   1481643
weighted avg       0.75      0.75      0.75   1481643

In [64]:
from scipy import stats
np.count_nonzero(y_test)

80395

# 04_b. Penalised